### ISSUE TITLE
AttributeError: 'module' object has no attribute 'SSL_ST_INIT'

### ISSUE THREAD

**Issue by rpuntaie** [sudoforge/pkgbuilds#13]
On Archlinux.

I googled and tried several offered "solutions" without success,
e.g. https://github.com/google/grr/issues/704

```
sudo python2 -m easy_install --upgrade pyOpenSSL==16.2.0
```
also without the `==16.2.0`

`easy_install` because `sudo pip2 uninstall pyopenssl` leads to the same problem.

Here is the traceback

```
Traceback (most recent call last):
  File "/home/roland/.local/var/cache/yay/google-cloud-sdk/pkg/google-cloud-sdk/opt/google-cloud-sdk/bin/bootstrapping/install.py", line 12, in <module>
    import bootstrapping
  File "/home/roland/.local/var/cache/yay/google-cloud-sdk/pkg/google-cloud-sdk/opt/google-cloud-sdk/bin/bootstrapping/bootstrapping.py", line 44, in <module>
    from googlecloudsdk.core.credentials import store as c_store
  File "/home/roland/.local/var/cache/yay/google-cloud-sdk/pkg/google-cloud-sdk/opt/google-cloud-sdk/lib/googlecloudsdk/core/credentials/store.py", line 36, in <modu
le>
    from googlecloudsdk.core.credentials import creds
  File "/home/roland/.local/var/cache/yay/google-cloud-sdk/pkg/google-cloud-sdk/opt/google-cloud-sdk/lib/googlecloudsdk/core/credentials/creds.py", line 30, in <modu
le>
    from googlecloudsdk.core.credentials import devshell as c_devshell
  File "/home/roland/.local/var/cache/yay/google-cloud-sdk/pkg/google-cloud-sdk/opt/google-cloud-sdk/lib/googlecloudsdk/core/credentials/devshell.py", line 30, in <m
odule>
    from oauth2client import client
  File "/home/roland/.local/var/cache/yay/google-cloud-sdk/pkg/google-cloud-sdk/opt/google-cloud-sdk/lib/third_party/oauth2client/client.py", line 52, in <module>
    from oauth2client import crypt
  File "/home/roland/.local/var/cache/yay/google-cloud-sdk/pkg/google-cloud-sdk/opt/google-cloud-sdk/lib/third_party/oauth2client/crypt.py", line 41, in <module>
    from oauth2client import _openssl_crypt
  File "/home/roland/.local/var/cache/yay/google-cloud-sdk/pkg/google-cloud-sdk/opt/google-cloud-sdk/lib/third_party/oauth2client/_openssl_crypt.py", line 16, in <mo
dule>
    from OpenSSL import crypto
  File "/usr/lib/python2.7/site-packages/OpenSSL/__init__.py", line 8, in <module>
    from OpenSSL import rand, crypto, SSL
  File "/usr/lib/python2.7/site-packages/OpenSSL/SSL.py", line 105, in <module>
    SSL_ST_INIT = _lib.SSL_ST_INIT
AttributeError: 'module' object has no attribute 'SSL_ST_INIT'
==> ERROR: A failure occurred in package().
    Aborting...

```

**Comment by sudoforge** [comment]
When people have encountered errors similar to this before, it has been due to the fact that they have installed some lib via `pip` providing a library that the SDK uses.

This is not recreatable in a clean environment.

For a start, remove the `pyOpenSSL` package that you installed in an attempt to resolve this error. Now, what other libraries have you installed via pip?

**Comment by rpuntaie** [comment]
I actually tried now on a clean Arch installation and there were no problem. I close this. Thanks for the remark.

**Comment by sudoforge** [comment]
@rpuntaie Thanks for being proactive about that. I'm still happy to help you debug -- after all, this isn't the first time something like this has happened for a user, and if there's something I can do to prevent it in the future I'd gladly do so.

**Comment by rpuntaie** [comment]
I had a ``/usr/lib/python2.7/site-packages/OpenSSL/version.py`` with version 0.14.
I don't know how it came there. ``pip2`` did not work.

``sudo python2 -m easy_install --upgrade PyOpenSSL`` said it was already up-to-date.
Probably because of the parallel ``../pyOpenSSL-19.1.0-py2.7.egg/OpenSSL``.

I did a ``sudo rm -rf /usr/lib/python2.7/site-packages/OpenSSL /usr/lib/python2.7/site-packages/PyOpenSSL-*``
then ``sudo python2 -m easy_install --upgrade PyOpenSSL``.

Now ``pip2`` works again, e.g. ``sudo pip2 install --upgrade  pyopenssl`` does not produce the above error any more.
The new location of PyOpenSSL is ``../pyOpenSSL-19.1.0-py2.7.egg/OpenSSL`` with version ``19.1.0``.
