### ISSUE TITLE
Error updating google-cloud-sdk

### ISSUE THREAD

**Issue by ruben-farma** [sudoforge/pkgbuilds#14]
I'm updating from bauh and this is the output:

```mkdir -p /tmp/bauh/aur/build_1578902844

wget https://aur.archlinux.org/cgit/aur.git/snapshot/google-cloud-sdk.tar.gz

--2020-01-13 09:07:24--  https://aur.archlinux.org/cgit/aur.git/snapshot/google-cloud-sdk.tar.gz
Loaded CA certificate '/etc/ssl/certs/ca-certificates.crt'
Resolving aur.archlinux.org (aur.archlinux.org)... 5.9.250.164, 2a01:4f8:160:3033::2
Connecting to aur.archlinux.org (aur.archlinux.org)|5.9.250.164|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: unspecified [application/x-gzip]
Saving to: 'google-cloud-sdk.tar.gz'
0K .                                                      35.9M=0s
2020-01-13 09:07:25 (35.9 MB/s) - 'google-cloud-sdk.tar.gz' saved [1862]
tar xvzf google-cloud-sdk.tar.gz

google-cloud-sdk/
google-cloud-sdk/.SRCINFO
google-cloud-sdk/PKGBUILD
google-cloud-sdk/google-cloud-sdk.sh
Using custom makepkg.conf -> /home/ruben/.config/bauh/arch/makepkg.conf
makepkg -ALcf --check --noarchive --nobuild --noprepare --config=/home/ruben/.config/bauh/arch/makepkg.conf

==> Making package: google-cloud-sdk 275.0.0-1 (Mon Jan 13 09:07:25 2020)
==> Checking runtime dependencies...
==> Checking buildtime dependencies...
==> Retrieving sources...
-> Downloading google-cloud-sdk_275.0.0.orig.tar.gz...
% Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
Dload  Upload   Total   Spent    Left  Speed
0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
 70 31.2M   70 22.0M    0     0  30.1M      0  0:00:01 --:--:--  0:00:01 30.1M
100 31.2M  100 31.2M    0     0  37.7M      0 --:--:-- --:--:-- --:--:-- 37.6M
-> Found google-cloud-sdk.sh
==> Validating source files with sha256sums...
google-cloud-sdk_275.0.0.orig.tar.gz ... Passed
google-cloud-sdk.sh ... Passed
==> Extracting sources...
-> Extracting google-cloud-sdk_275.0.0.orig.tar.gz with bsdtar
bsdtar: Failed to set default locale
==> Sources are ready.
Using custom makepkg.conf -> /home/ruben/.config/bauh/arch/makepkg.conf
makepkg -ALcsmf --config=/home/ruben/.config/bauh/arch/makepkg.conf

==> Making package: google-cloud-sdk 275.0.0-1 (Mon Jan 13 09:07:28 2020)
==> Checking runtime dependencies...
==> Checking buildtime dependencies...
==> Retrieving sources...
-> Found google-cloud-sdk_275.0.0.orig.tar.gz
-> Found google-cloud-sdk.sh
==> Validating source files with sha256sums...
google-cloud-sdk_275.0.0.orig.tar.gz ... Passed
google-cloud-sdk.sh ... Passed
==> Extracting sources...
-> Extracting google-cloud-sdk_275.0.0.orig.tar.gz with bsdtar
bsdtar: Failed to set default locale
==> Entering fakeroot environment...
==> Starting package()...
Copying core SDK components
Running bootstrapping script
Traceback (most recent call last):
File "/tmp/bauh/aur/build_1578902844/google-cloud-sdk/pkg/google-cloud-sdk/opt/google-cloud-sdk/lib/googlecloudsdk/core/util/files.py", line 1227, in _FileOpener
return io.open(path, mode, encoding=encoding)
PermissionError: [Errno 13] Permission denied: '/root/.config/gcloud/active_config'
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
File "/tmp/bauh/aur/build_1578902844/google-cloud-sdk/pkg/google-cloud-sdk/opt/google-cloud-sdk/lib/googlecloudsdk/core/configurations/named_configs.py", line 485, in _ActiveConfigNameFromFile
config_name = file_utils.ReadFileContents(path)
File "/tmp/bauh/aur/build_1578902844/google-cloud-sdk/pkg/google-cloud-sdk/opt/google-cloud-sdk/lib/googlecloudsdk/core/util/files.py", line 1060, in ReadFileContents
with FileReader(path) as f:
File "/tmp/bauh/aur/build_1578902844/google-cloud-sdk/pkg/google-cloud-sdk/opt/google-cloud-sdk/lib/googlecloudsdk/core/util/files.py", line 1163, in FileReader
return _FileOpener(path, 'rt', 'read', encoding='utf8')
File "/tmp/bauh/aur/build_1578902844/google-cloud-sdk/pkg/google-cloud-sdk/opt/google-cloud-sdk/lib/googlecloudsdk/core/util/files.py", line 1234, in _FileOpener
raise exc_type('Unable to {0} file [{1}]: {2}'.format(verb, path, e))
googlecloudsdk.core.util.files.Error: Unable to read file [/root/.config/gcloud/active_config]: [Errno 13] Permission denied: '/root/.config/gcloud/active_config'
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
File "/tmp/bauh/aur/build_1578902844/google-cloud-sdk/pkg/google-cloud-sdk/opt/google-cloud-sdk/bin/bootstrapping/install.py", line 12, in <module>
import bootstrapping
File "/tmp/bauh/aur/build_1578902844/google-cloud-sdk/pkg/google-cloud-sdk/opt/google-cloud-sdk/bin/bootstrapping/bootstrapping.py", line 40, in <module>
from googlecloudsdk.core import execution_utils
File "/tmp/bauh/aur/build_1578902844/google-cloud-sdk/pkg/google-cloud-sdk/opt/google-cloud-sdk/lib/googlecloudsdk/core/execution_utils.py", line 34, in <module>
from googlecloudsdk.core import log
File "/tmp/bauh/aur/build_1578902844/google-cloud-sdk/pkg/google-cloud-sdk/opt/google-cloud-sdk/lib/googlecloudsdk/core/log.py", line 817, in <module>
_log_manager = _LogManager()
File "/tmp/bauh/aur/build_1578902844/google-cloud-sdk/pkg/google-cloud-sdk/opt/google-cloud-sdk/lib/googlecloudsdk/core/log.py", line 559, in __init__
self.Reset(sys.stdout, sys.stderr)
File "/tmp/bauh/aur/build_1578902844/google-cloud-sdk/pkg/google-cloud-sdk/opt/google-cloud-sdk/lib/googlecloudsdk/core/log.py", line 572, in Reset
std_console_formatter = _ConsoleFormatter(stderr)
File "/tmp/bauh/aur/build_1578902844/google-cloud-sdk/pkg/google-cloud-sdk/opt/google-cloud-sdk/lib/googlecloudsdk/core/log.py", line 362, in __init__
use_color = not properties.VALUES.core.disable_color.GetBool(validate=False)
File "/tmp/bauh/aur/build_1578902844/google-cloud-sdk/pkg/google-cloud-sdk/opt/google-cloud-sdk/lib/googlecloudsdk/core/properties.py", line 2122, in GetBool
named_configs.ActivePropertiesFile.Load(),
File "/tmp/bauh/aur/build_1578902844/google-cloud-sdk/pkg/google-cloud-sdk/opt/google-cloud-sdk/lib/googlecloudsdk/core/configurations/named_configs.py", line 396, in Load
[config.Paths().installation_properties_path, ActiveConfig(
File "/tmp/bauh/aur/build_1578902844/google-cloud-sdk/pkg/google-cloud-sdk/opt/google-cloud-sdk/lib/googlecloudsdk/core/configurations/named_configs.py", line 436, in ActiveConfig
config_name = _EffectiveActiveConfigName()
File "/tmp/bauh/aur/build_1578902844/google-cloud-sdk/pkg/google-cloud-sdk/opt/google-cloud-sdk/lib/googlecloudsdk/core/configurations/named_configs.py", line 461, in _EffectiveActiveConfigName
config_name = _ActiveConfigNameFromFile()
File "/tmp/bauh/aur/build_1578902844/google-cloud-sdk/pkg/google-cloud-sdk/opt/google-cloud-sdk/lib/googlecloudsdk/core/configurations/named_configs.py", line 497, in _ActiveConfigNameFromFile
raise NamedConfigFileAccessError(
googlecloudsdk.core.configurations.named_configs.NamedConfigFileAccessError: Active configuration name could not be read from: [/root/.config/gcloud/active_config]. Ensure you have sufficient read permissions on required active configuration in [/root/.config/gcloud/configurations].
Unable to read file [/root/.config/gcloud/active_config]: [Errno 13] Permission denied: '/root/.config/gcloud/active_config'
==> ERROR: A failure occurred in package().
Aborting...
Could not find generated .tar.xz file. Aborting...
rm -rf /tmp/bauh/aur/build_1578902844
```
I checked:
```
bsdtar --version
bsdtar 3.4.0 - libarchive 3.4.0 zlib/1.2.11 liblzma/5.2.4 bz2lib/1.0.8 liblz4/1.9.2 libzstd/1.4.3
``` 
Also:
```
type bsdtar
bsdtar está asociado (/usr/bin/bsdtar)
```

And extract manually:
bsdtar -x -f google-cloud-sdk_275.0.0.orig.tar.gz -> Works OK:
```
/tmp/google-cloud-sdk$ ls -la
total 492
drwxr-xr-x 10 ruben ruben    440 ene  3 16:52 .
drwxrwxrwt 30 root  root    1000 ene 13 09:41 ..
drwxr-xr-x  3 ruben ruben    220 ene  3 16:52 bin
-rw-r--r--  1 ruben ruben   2711 ene  3 16:50 completion.bash.inc
-rw-r--r--  1 ruben ruben   2083 ene  3 16:50 completion.zsh.inc
drwxr-xr-x  3 ruben ruben     60 ene  3 16:50 data
drwxr-xr-x  3 ruben ruben     60 ene  3 16:52 deb
drwxr-xr-x  3 ruben ruben     60 ene  3 16:52 help
drwxr-xr-x  3 ruben ruben    620 ene  3 16:52 .install
-rwxr-xr-x  1 ruben ruben   7025 ene  3 16:50 install.bat
-rwxr-xr-x  1 ruben ruben   6455 ene  3 16:50 install.sh
drwxr-xr-x  6 ruben ruben    140 ene  3 16:50 lib
-rw-r--r--  1 ruben ruben    980 ene  3 16:50 LICENSE
-rw-r--r--  1 ruben ruben    377 ene  3 16:50 path.bash.inc
-rw-r--r--  1 ruben ruben   1210 ene  3 16:50 path.fish.inc
-rw-r--r--  1 ruben ruben     31 ene  3 16:50 path.zsh.inc
drwxr-xr-x  5 ruben ruben    100 ene  3 16:52 platform
-rw-r--r--  1 ruben ruben     39 ene  3 16:52 properties
-rw-r--r--  1 ruben ruben    673 ene  3 16:50 README
-rw-r--r--  1 ruben ruben 446563 ene  3 16:50 RELEASE_NOTES
drwxr-xr-x  3 ruben ruben     60 ene  3 16:52 rpm
-rw-r--r--  1 ruben ruben      8 ene  3 16:52 VERSION
```

Also, I don't know why I have this error:
googlecloudsdk.core.util.files.Error: Unable to read file [/root/.config/gcloud/active_config]: [Errno 13] Permission denied: '/root/.config/gcloud/active_config'

**Comment by sudoforge** [comment]
Can you build the package with `makepkg -sr` as your user, manually, and see if you can recreate this?

The fact that it's checking `/root` would seem to indicate that `bauh` is running as root; although I am unfamiliar with `bauh`, it appears to be an AUR helper and is not explicitly supported.

**Comment by ruben-farma** [comment]
I build the package google-cloud-sdk-275.0.0-1-x86_64.pkg.tar.xz correctly.

```
ruben@ruben-elitebook:/tmp/build$ makepkg -sr
==> Creando el paquete: google-cloud-sdk 275.0.0-1 (lun 13 ene 2020 11:22:08 CET)
==> Comprobando dependencias mientras se ejecuta...
==> Comprobando dependencias mientras se compila...
==> Recibiendo las fuentes...
  -> Descargando google-cloud-sdk_275.0.0.orig.tar.gz...
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100 31.2M  100 31.2M    0     0  34.2M      0 --:--:-- --:--:-- --:--:-- 34.1M
  -> google-cloud-sdk.sh ha sido encontrado 
==> Validando los archivos source con sha256sums...
    google-cloud-sdk_275.0.0.orig.tar.gz ... Aprobado
    google-cloud-sdk.sh ... Aprobado
==> Extrayendo las fuentes...
  -> Extrayendo google-cloud-sdk_275.0.0.orig.tar.gz con bsdtar
==> Entrando en entorno fakeroot...
==> Iniciando package()...
Copying core SDK components
Running bootstrapping script
/tmp/build/pkg/google-cloud-sdk/opt/google-cloud-sdk/lib/googlecloudsdk/core/console/console_io.py:544: SyntaxWarning: "is" with a literal. Did you mean "=="?
  if answer is None or (answer is '' and default is not None):
Cleaning up artifacts of the bootstrap script
Setting up profile environment variables
Installing bash completion script==> Creando el paquete «google-cloud-sdk»...
  -> Generando el archivo .PKGINFO...
  -> Generando el archivo .BUILDINFO...
  -> Generando el archivo .MTREE...
  -> Comprimiendo el paquete...
==> Abandonando el entorno fakeroot.
==> Compilación terminada: google-cloud-sdk 275.0.0-1 (lun 13 ene 2020 11:24:25 CET)

Installing man pages
Creating symlinks for applications
Fixing file permissions
==> Depurando la instalación...
  -> Quitando los archivos libtool...
  -> Purgando los archivos innecesarios...
  -> Comprimiendo las páginas del manual y de información...

==> Buscando problemas de empaquetado...
==> ADVERTENCIA: El paquete contiene referencias a $pkgdir
some files...

==> Creando el paquete «google-cloud-sdk»...
  -> Generando el archivo .PKGINFO...
  -> Generando el archivo .BUILDINFO...
  -> Generando el archivo .MTREE...
  -> Comprimiendo el paquete...
==> Abandonando el entorno fakeroot.
==> Compilación terminada: google-cloud-sdk 275.0.0-1 (lun 13 ene 2020 11:24:25 CET)

```

**Comment by sudoforge** [comment]
@ruben-farma The error you're encountering is occurring within `bauh` -- it appears that it is running some part of the process as `root`. This is apparent due to the fact that the bootstrapping script is attempting to open `/root/.config/gcloud/active_config`, instead of `/home/$USER/.config/gcloud/active_config`.

While I'd love to help you out, there is unfortunately nothing I can do within the scope of this package to support `bauh`. I recommend that you file an issue with the maintainers of `bauh`; you did a great job providing all of the necessary information here -- doing the same for them would be a good idea!

Feel free to reference this issue within the issue you file under the `bauh` project, so that the maintainers have the full context of the error.

In the mean time, you can manage the package manually, as your own user:

* `makepkg -sri` will install a package's build dependencies, build the package, remove the builddeps, and then install the package.
* `sudo pacman -U <file>` will install a package with the given filename.

I personally run my own Pacman repository with AUR packages. The helper I use ([`aurutils`](https://github.com/AladW/aurutils)) does not run as root and therefore will not encounter the same class of errors you are currently experiencing. I'd be happy to talk about this more in depth if you're interested and need some additional help setting it up for yourself.
