### ISSUE TITLE
google-cloud-sdk needs python-ruamel-yaml to build

### ISSUE THREAD

**Issue by kubrickfr** [sudoforge/pkgbuilds#44]
Similar to #6 but no need to install an aur version of python-ruamel-yaml

```
Traceback (most recent call last):
  File "/home/me/.cache/pikaur/build/google-cloud-sdk/pkg/google-cloud-sdk/opt/google-cloud-sdk/bin/bootstrapping/install.py", line 12, in <module>
    import bootstrapping
  File "/home/me/.cache/pikaur/build/google-cloud-sdk/pkg/google-cloud-sdk/opt/google-cloud-sdk/bin/bootstrapping/bootstrapping.py", line 46, in <module>
    from googlecloudsdk.core.updater import update_manager
  File "/home/me/.cache/pikaur/build/google-cloud-sdk/pkg/google-cloud-sdk/opt/google-cloud-sdk/lib/googlecloudsdk/core/updater/update_manager.py", line 36, in <module>
    from googlecloudsdk.core import yaml
  File "/home/me/.cache/pikaur/build/google-cloud-sdk/pkg/google-cloud-sdk/opt/google-cloud-sdk/lib/googlecloudsdk/core/yaml.py", line 31, in <module>
    from googlecloudsdk.core import yaml_location_value
  File "/home/me/.cache/pikaur/build/google-cloud-sdk/pkg/google-cloud-sdk/opt/google-cloud-sdk/lib/googlecloudsdk/core/yaml_location_value.py", line 39, in <module>
    from ruamel import yaml
ImportError: cannot import name 'yaml' from 'ruamel' (unknown location)
```

**Comment by sudoforge** [comment]
Similar to #6, this is not reproducible in a chroot. As with most Google things, dependencies that `google-cloud-sdk` needs to bootstrap are bundled within the tarball for convenience. We can see this by traversing the archive for the current version:

```
/tmp
➜ curl -Lo google-cloud-sdk-338.0.0.tar.gz https://dl.google.com/dl/cloudsdk/release/downloads/for_packagers/linux/google-cloud-sdk_338.0.0.orig.tar.gz
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100 84.1M  100 84.1M    0     0  25.3M      0  0:00:03  0:00:03 --:--:-- 25.3M


/tmp
➜ tar xf google-cloud-sdk-338.0.0.tar.gz


/tmp
➜ cd google-cloud-sdk


/tmp
➜ tree -a google-cloud-sdk/lib/third_party/ruamel
google-cloud-sdk/lib/third_party/ruamel
├── LICENSE
├── __init__.py
└── yaml
    ├── __init__.py
    ├── anchor.py
    ├── comments.py
    ├── compat.py
    ├── composer.py
    ├── configobjwalker.py
    ├── constructor.py
    ├── cyaml.py
    ├── dumper.py
    ├── emitter.py
    ├── error.py
    ├── events.py
    ├── loader.py
    ├── main.py
    ├── nodes.py
    ├── parser.py
    ├── reader.py
    ├── representer.py
    ├── resolver.py
    ├── scalarbool.py
    ├── scalarfloat.py
    ├── scalarint.py
    ├── scalarstring.py
    ├── scanner.py
    ├── serializer.py
    ├── setup.py
    ├── timestamp.py
    ├── tokens.py
    └── util.py

1 directory, 31 files
```

Furthermore, the build completes successfully in a chroot:

<details><summary>build output (click to expand)</summary><p>

```
gh::source/third_party/aur/google-cloud-sdk [ trunk * ]
➜ aur chroot -B
==> Synchronizing chroot copy [/var/lib/aurbuild/x86_64/root] -> [sudoforge]...done
==> Making package: google-cloud-sdk 338.0.0-1 (2021-04-29T06:02:10 MDT)
==> Retrieving sources...
  -> Downloading google-cloud-sdk_338.0.0.orig.tar.gz...
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100 84.1M  100 84.1M    0     0  25.0M      0  0:00:03  0:00:03 --:--:-- 25.0M
  -> Found google-cloud-sdk.sh
  -> Found 0001-set-python2-for-dev-appserver-py.patch
  -> Found 0002-set-python2-for-endpointscfg-py.patch
  -> Found 0003-add-compdef-to-zsh-completion.patch
==> Validating source files with sha256sums...
    google-cloud-sdk_338.0.0.orig.tar.gz ... Passed
    google-cloud-sdk.sh ... Passed
    0001-set-python2-for-dev-appserver-py.patch ... Passed
    0002-set-python2-for-endpointscfg-py.patch ... Passed
    0003-add-compdef-to-zsh-completion.patch ... Passed
==> Making package: google-cloud-sdk 338.0.0-1 (Thu 29 Apr 2021 06:02:18 AM MDT)
==> Checking runtime dependencies...
==> Installing missing dependencies...
resolving dependencies...
looking for conflicting packages...

Packages (2) libnsl-1.3.0-2  python-3.9.4-1

Total Installed Size:  79.51 MiB

:: Proceed with installation? [Y/n]
(2/2) checking keys in keyring                                           [########################################] 100%
(2/2) checking package integrity                                         [########################################] 100%
(2/2) loading package files                                              [########################################] 100%
(2/2) checking for file conflicts                                        [########################################] 100%
:: Processing package changes...
(1/2) installing libnsl                                                  [########################################] 100%
(2/2) installing python                                                  [########################################] 100%
Optional dependencies for python
    python-setuptools
    python-pip
    sqlite [installed]
    mpdecimal: for decimal
    xz: for lzma [installed]
    tk: for tkinter
==> Checking buildtime dependencies...
==> Retrieving sources...
  -> Found google-cloud-sdk_338.0.0.orig.tar.gz
  -> Found google-cloud-sdk.sh
  -> Found 0001-set-python2-for-dev-appserver-py.patch
  -> Found 0002-set-python2-for-endpointscfg-py.patch
  -> Found 0003-add-compdef-to-zsh-completion.patch
==> WARNING: Skipping all source file integrity checks.
==> Extracting sources...
  -> Extracting google-cloud-sdk_338.0.0.orig.tar.gz with bsdtar
==> Starting prepare()...
==> Entering fakeroot environment...
==> Starting package()...
==> Source [/build/google-cloud-sdk/pkg/google-cloud-sdk/opt/google-cloud-sdk/completion.bash.inc] in your profile to enable shell command completion for gcloud.
==> Source [/build/google-cloud-sdk/pkg/google-cloud-sdk/opt/google-cloud-sdk/path.bash.inc] in your profile to add the Google Cloud SDK command line tools to your $PATH.
==> Tidying install...
  -> Removing libtool files...
  -> Purging unwanted files...
  -> Compressing man and info pages...
==> Checking for packaging issues...
==> Creating package "google-cloud-sdk"...
  -> Generating .PKGINFO file...
  -> Generating .BUILDINFO file...
  -> Generating .MTREE file...
  -> Compressing package...
==> Leaving fakeroot environment.
==> Finished making: google-cloud-sdk 338.0.0-1 (Thu 29 Apr 2021 06:06:01 AM MDT)
aur chroot -B  292.55s user 105.49s system 170% cpu 3:52.94 total
```
</p></details>

**Comment by sudoforge** [comment]
I would love to work with you to figure out why the bundled `ruamel.yaml` is not being sourced correctly for you. My first guess here is that you may have some version of `ruamel` installed on your system.

Can you run the following commands and paste their output in a reply?

* `python -V && command -v python`
* `pacman -Q | grep ruamel`
* `pip list | grep ruamel`
* `sudo pip list | grep ruamel`

**Comment by kubrickfr** [comment]
```
$ python -V && command -v python
Python 3.9.4
/usr/bin/python
```

```
$ pacman -Q | grep ruamel
python-ruamel.yaml.clib 0.2.2-3
```

```
$ pip list | grep ruamel
/home/me/.local/lib/python3.9/site-packages/secretstorage/dhcrypto.py:16: CryptographyDeprecationWarning: int_from_bytes is deprecated, use int.from_bytes instead
  from cryptography.utils import int_from_bytes
/home/me/.local/lib/python3.9/site-packages/secretstorage/util.py:25: CryptographyDeprecationWarning: int_from_bytes is deprecated, use int.from_bytes instead
  from cryptography.utils import int_from_bytes
ruamel.yaml.clib              0.2.2
ruamel.zip2tar                0.4
```

```
$ env | grep PYTHON
CLOUDSDK_PYTHON_ARGS=-S
CLOUDSDK_PYTHON=python
```

**Comment by sudoforge** [comment]
Right, so you have a version of the ruamel lib already installed, which is being picked up instead of the bundled dep.

Unfortunately, your version doesn't have the necessary module(s).

I'll work out a solution for this today, but as a workaround, you should be able to build successfully if you remove the ruamel packages you have installed, both through pacman and pip if necessary.

**Comment by sudoforge** [comment]
Or, alternatively, you can [build it in a clean chroot](https://wiki.archlinux.org/index.php/DeveloperWiki:Building_in_a_clean_chroot).

**Comment by kubrickfr** [comment]
Thank you. Yes, I had managed to build it by installing yet another version :-)

But I'm still reporting it because I think the build system should be more robust (although python is a notorious mess and definitely not your fault).
