### ISSUE TITLE
google-cloud-sdk error in package() "cannot import name yaml"

### ISSUE THREAD

**Issue by l-lotz** [sudoforge/pkgbuilds#6]
I get the following error in package():
```  -> Copying core SDK components
  -> Running bootstrapping script and adding additional components
Traceback (most recent call last):
  File "/home/linus/.cache/yay/google-cloud-sdk/pkg/google-cloud-sdk/opt/google-cloud-sdk/bin/bootstrapping/install.py", line 12, in <module>
    import bootstrapping
  File "/home/linus/.cache/yay/google-cloud-sdk/pkg/google-cloud-sdk/opt/google-cloud-sdk/bin/bootstrapping/bootstrapping.py", line 46, in <module>
    from googlecloudsdk.core.updater import update_manager
  File "/home/linus/.cache/yay/google-cloud-sdk/pkg/google-cloud-sdk/opt/google-cloud-sdk/lib/googlecloudsdk/core/updater/update_manager.py", line 35, in <module>
    from googlecloudsdk.core import yaml
  File "/home/linus/.cache/yay/google-cloud-sdk/pkg/google-cloud-sdk/opt/google-cloud-sdk/lib/googlecloudsdk/core/yaml.py", line 29, in <module>
    from googlecloudsdk.core import yaml_location_value
  File "/home/linus/.cache/yay/google-cloud-sdk/pkg/google-cloud-sdk/opt/google-cloud-sdk/lib/googlecloudsdk/core/yaml_location_value.py", line 39, in <module>
    from ruamel import yaml
```
I fixed it by installing aur/python2-ruamel-yaml from AUR. Maybe this should be added to the makedepends or depends of the PKGBUILD. Unfortunately python2-ruamel-yaml has been marked out-of-date for a while.

**Comment by sudoforge** [comment]
I'm unable to recreate this. Closing as `invalid`.
